### ISSUE TITLE
Raspberry Debian Jessie No module named cli error

### ISSUE THREAD

**Issue by reset12** [nrocco/smeterd#15]
Hello, 
i got the following Error:

Traceback (most recent call last):
  File "/usr/local/bin/smeterd", line 11, in <module>
    load_entry_point('smeterd==2.6.0', 'console_scripts', 'smeterd')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named cli

What i must install to solve this error ?

**Comment by nrocco** [comment]
Hi @reset12,

I notice I have similar errors after a fresh `pip install smeterd` in a python 2.7 based virtualenv.
I am investigating why this happens.

**Comment by nrocco** [comment]
I just fixed the issue. The problem was how the `.tar.gz` was created for uploading to pypi.

I have just created and uploaded a new version `2.6.1` to pypi. It may take a while before your `pip` picks it up.

Apologies for the inconvenience and thanks for submitting this issue.

**Comment by reset12** [comment]
Hello,
i have now installed the new Version smeterd 2.7.1


root@raspi-Stetten:/home/hugo# cat /dev/ttyUSB0     
root@raspi-Stetten:/home/hugo# stty -F /dev/ttyUSB0 1:0:8bd:0:3:1c:7f:15:4:5:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
root@raspi-Stetten:/home/hugo# cat /dev/ttyUSB0
N
\�Fbbrc�D�
          EMH~�!c��v
\�Gbbrcw
        EMH~�!b
��rbe��ww��ǂ�EMHw       �
                         EMH~�!�d�bR�V����bR�V����bR�Vw�b�U�w��ǂ�rbe����
                                                                        u
����?�l}�~c��v#�1�N���=����]#�d'
\�Jbbrcqc�q▒ͥ
\�Lbbrc�D�
          EMH~�!ct�v
\�Mbbrcw
        EMH~�!b
��rbe��!ww��ǂ�EMHw      �
                         EMH~�!�d�bR�V����bR�V����bR�Vw�b�U�w��ǂ�rbe��!��
                                                                         u
����?�l}�~c��v#�1�N���=����]#�d'
\�Pbbrcqc/▒з^C
root@raspi-Stetten:/home/hugo# smeterd -v read-meter
[2016-12-12 07:24:35,151] INFO New serial connection opened to /dev/ttyUSB0
[2016-12-12 07:24:35,156] INFO Start reading lines


The smeterd doesnt read any information.

When i try it with stty and cat, the sensor gives response.

Do you have any hints for me ?

with regards
Bruno

**Comment by nrocco** [comment]
@reset12 it looks to me that you need to play around with the `--serial` command line options. Are you sure that you are using the correct baudrate, parity, bits etc for the serial connection for you meter?
