### ISSUE TITLE
fyi using smeterd as a base

### ISSUE THREAD

**Issue by mpvader** [nrocco/smeterd#18]
Hi @nrocco,

just fyi: I've made a P1 plugin for our Venus OS:

https://github.com/mpvader/dbus-p1/

Thanks for the nice & simple code, especially for making it so easy to use as a module in Python.

**Comment by mpvader** [comment]
ps sorry for misusing an issue for this. You're welcome to close this ofcourse.

**Comment by nrocco** [comment]
Hi @mpvader, thanks for letting me know it's useful.
