### ISSUE TITLE
Expose gas meter time stamp

### ISSUE THREAD

**Issue by ot3** [nrocco/smeterd#19]
I've looked at the (very nice) code but can't find a way to extract the gas meter timestamp. Am I correct in that this is not available? If I'm wrong, please let me know how to get it. If not available then please consider this as a feature request with the timestamp preferably as a UNIX timestamp (seconds since epoch)

**Comment by nrocco** [comment]
Hi there,

When I look at the P1 packets from my smart meter there is no gas meter timestamp. 

It might be that other meters expose such a value. Getting sample P1 packets would be very helpful in that case.

**Comment by ot3** [comment]
Interesting. In the DSMR specification, the time stamp is mandatory.

Here's a sample datagram with some identifying information removed:

```
pi@eon:[~]: smeterd read-meter --raw
/KMP5 ZABFxxx
0-0:96.1.1(xxx)
1-0:1.8.1(06007.111*kWh)
1-0:1.8.2(03918.394*kWh)
1-0:2.8.1(03127.410*kWh)
1-0:2.8.2(07082.845*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(0000.04*kW)
1-0:2.7.0(0000.00*kW)
0-0:96.13.1()
0-0:96.13.0()
0-1:24.1.0(3)
0-1:96.1.0(yyy)
0-1:24.3.0(180119100000)(00)(60)(1)(0-1:24.2.1)(m3)
(05676.653)
!
```

The gas timestamp is 180119100000.

**Comment by nrocco** [comment]
@ot3 you are absolutely right. I assumed it was a timestmap and could not make sense of the value. I tried to read about the P1 telegram spec but could not find any details on what this value is.

I will work on a PR to get this value parsed and exposed via this library.

**Comment by nrocco** [comment]
@ot3 I have created a pull request which adds this timestamp to the library and cli stdout.

**Comment by nrocco** [comment]
@ot3 The new version `2.7.3` is now available via pypi.

```[root@server ~]# smeterd read-meter
Time                      2018-01-21 19:48:13.094529
Total kWh High consumed   350778
Total kWh Low consumed    243758
Total gas consumed        9394370
Current kWh tariff        1
Gas Measured At           1516564800
```

Thanks for suggesting this improvement!

**Comment by ot3** [comment]
@nrocco Thanks! I just implemented the new version and it works like a charm.

**Comment by nrocco** [comment]
Good to hear @ot3
