### ISSUE TITLE
Can't get Kaifa meter to work. 

### ISSUE THREAD

**Issue by rewolff** [nrocco/smeterd#6]
Got a new meter friday, however I can't get this to work. 
Every time I fix something the next thing pops up. 
My meter is the latest protocol version, so runs at 115200 baud. Similarly, if the meter isn't on /dev/ttyUSB0, the program is a hassle to use if that cannot be configured but has to be provided on each commandline. 

I got it so far as to start parsing stuff but then when it tried to convert stuff to kwh by multiplying by 1000, I get a "nonetype" that cannot be multiplied. This means that the error is somewhere else and my python is iinsufficient to trace where things go wrong.

**Comment by rewolff** [comment]
Here is a message from my meter to aid in further debugging. 
[smartmeter.txt](https://github.com/nrocco/smeterd/files/355999/smartmeter.txt)
I'v blacked out some serial numbers as I've seen others do. The x's represent digits, their number is correct.

**Comment by nrocco** [comment]
Hi rewolff,

Thanks for providing sample output. As soon as I am near a workstation I will do some troubleshooting. 

-- 
Nico Di Rocco

**Comment by rewolff** [comment]
Note that I have  a "Kaifa" and that there is still a pull request open said to improve things for a kaifa. 
I have the 105C, where the C denotes the latest version with 115k2 serial and latest updates to the protocol. (IIRC, some units were adjusted from Wh to kWh. things like that).

**Comment by nrocco** [comment]
@rewolff I have just merged to pull requests into master and created a new tag and published it here

https://pypi.python.org/pypi/smeterd/2.4.0

Can you try now?

**Comment by Atrejoe** [comment]
Reading the telegram, I think a some of @rewolff s issues are resolved in #8 (reading the gas meter)
The parsing of the kWh is a localization issue I think. Our meters seem to have a . for decimal seperator and this is interpreted as a thousand separator, but i'd have to investigate that and make a separate issue.
